### ISSUE TITLE
caver.klay.accounts.decrypt function doesn't work as expected

### ISSUE THREAD

**Issue by devhyunjae** [klaytn/caver-js#404] opened 2020-12-15 02:21 UTC
# DEMO

https://codesandbox.io/s/serene-pare-05puk?file=/src/App.js

**Describe the bug**

`caver.klay.accounts.decrypt` throws unexpected error when executed multiple times.
`Invalid keystore V3 format: 'crypto' is not defined.`

It should only throw this error
`Key derivation failed - possibly wrong password`

**How to reproduce**
1. Click the demo app above
2. Check out the given json file
3. Press the DECRPYT! button
4. Check out the keyjson again. It has been **manipulated**. crypoto field has been changed to keyring field
5. Press the DECRPYT! button
6. Now it will show a different error

**Expected behavior**
It should only throw this error
`Key derivation failed - possibly wrong password`

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.
<img width="1343" alt="Screen Shot 2020-12-15 at 11 12 38 AM" src="https://user-images.githubusercontent.com/12890257/102159808-968a6b80-3ec7-11eb-9c2a-007435330f25.png">
<img width="1280" alt="Screen Shot 2020-12-15 at 11 13 04 AM" src="https://user-images.githubusercontent.com/12890257/102159805-95593e80-3ec7-11eb-87ce-3b55bb9e2bb9.png">
<img width="1296" alt="Screen Shot 2020-12-15 at 11 13 38 AM" src="https://user-images.githubusercontent.com/12890257/102159797-91c5b780-3ec7-11eb-987f-0ed9806b8ac6.png">

**Environment (please complete the following information)**
 - caver-js version or git revision that exhibits the issue 1.5.5
 - OS and its version [e.g. macOS/10.14] macOs/11.0.1

**Additional context**

**Comment by jimni1222** [comment] 2020-12-15 04:32
Hi, thank you for reporting the bug. :) 

This is a bug caused by modifying the original data right away when decrypting.
Modifications are included in the PR below, and when the PR is merged, the rc version is released and can be used.
https://github.com/klaytn/caver-js/pull/405

I will let you know when the rc version is released. Thank you so much :)

**Comment by jimni1222** [comment] 2020-12-15 06:20
This issue has been resolved in [caver-js v1.5.6-rc.6](https://www.npmjs.com/package/caver-js/v/1.5.6-rc.6), so i will close this issue.
If there is an unresolved issue, please feel free to open it again. :)

**Closed by jimni1222** 2020-12-15 06:20 UTC
Labels: issue/bug
